### ISSUE TITLE
Link in ProfileGithub.js is redirecting incorrectly

### ISSUE THREAD

**Issue by elTortuga** [bradtraversy/devconnector#12]
Clicking on a repo link redirects to within the application

![screen shot 2018-08-01 at 7 15 45 pm](https://user-images.githubusercontent.com/5906041/43558645-6227104a-95bf-11e8-8075-679a826692e2.png)

![screen shot 2018-08-01 at 7 15 59 pm](https://user-images.githubusercontent.com/5906041/43558650-69afed50-95bf-11e8-96e3-6d8c9636bff1.png)

The work around right now is to use an `<a>` tag instead of the `<Link>` tag but I would like to understand what could be causing this problem.

**Comment by elTortuga** [comment]
Just figured it out by using the [API for Link](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/Link.md)

`<Link to={{pathname: repo.html_url, replace: true}} className="text-info" target="_blank">`

**Comment by ajay-banstola** [comment]
path to change this:
client\src\components\profile\ProfileGithub.js Line 41
