### ISSUE TITLE
Heroku Deploy Cannot GET

### ISSUE THREAD

**Issue by Neuroforge** [bradtraversy/devconnector#39]
Hello,

I have deployed to Heroku and i can register and login as expected. But i cannot get anything.

Axios appears to return index.html when it is called and i debug the response returned to the axios call.

Could it be this?

```
if(process.env.NODE_ENV === 'production'){
  console.log("Building client");
  app.use(express.static('client/build'));
  app.get('*', (req, res)=>{
    res.sendFile(path.resolve(__dirname,'client','build','index.html'));
  });
}
```

Isn't this code telling the server to send the index.html file for all routes when using GET?

Regards,

Daniel

**Comment by 0791msolomon** [comment]
I'm having the same exact issue, were you able to figure out what was happening here?

**Comment by petercr** [comment]
Double check your routing. If you are getting a `CANNOT GET /` then it's definitely a routing issue. Make sure proxy settings are working too.

**Comment by 0791msolomon** [comment]
I'll check that out, thanks for the reply!

**Comment by petercr** [comment]
@Neuroforge I have it working on both Heroku and and Google's GCP. So the base code for serving up `index.html` definitely works.  
Yes the idea is that **ALL** the API requests go through the Front-End via `index.html`

**Comment by stevengewa** [comment]
i had the same issues but resolved
