### ISSUE TITLE
For mobile ????

### ISSUE THREAD

**Issue by snake-eye77** [bradtraversy/devconnector#41]
http://developerconnector3297.herokuapp.com/  -- i complete all course but it's not working on mobile  .
anyone can explain me how i brings devconnector in mobile ....

i think devconnector should have forgot password process anyone can tell me how can i implement and 
send me code ..... or your suggestion ..... :)

**Comment by snake-eye77** [comment]
compose(
    window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()
  )
becauise of this devconnector can not avalable on mobbile  . if i removed this then i's works ,
Not need to add  redux developer extension

**Comment by rimoslav** [comment]
Well you do need it to have Redux devtools extension working. Replace:
`const store = createStore(
  rootReducer,
  initialState,
  compose(
    applyMiddleware(...middleware),
    window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()
  )
);`
with:
`const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;

const store = createStore(
  rootReducer,
  initialState,
  composeEnhancers(applyMiddleware(...middleware))
);`
