### ISSUE TITLE
npm run client-install doesnt work

### ISSUE THREAD

**Issue by Ory4n** [bradtraversy/devconnector#5]
Hi the following command doesn't work in gitbash

**Comment by Ory4n** [comment]
so i have to manually install all the required modules

**Comment by bradtraversy** [comment]
I just cloned it on Windows 10 using Git bash ran 
npm install
npm run client-install

and it works fine I am just getting the error that there is no keys_dev file which you need to create with your MongoDB key. I did not push that to the repo. What errors are you getting. I need more info than "It doesnt work"
