### ISSUE TITLE
Issue on frontend: Error b is undefined

### ISSUE THREAD

**Issue by Ory4n** [bradtraversy/devconnector#7]
I get several issues on front end that gitbash does not report
![sketch](https://user-images.githubusercontent.com/27835855/40872467-c8a7561e-66a2-11e8-9e4e-161699220b97.png)

**Comment by Ory4n** [comment]
and i get no errors or warnings in the terminal window, only on front-end

**Comment by galishmann** [comment]
This error happens in browser without Redux Devtools Extension. To solve this problem you must change store.js like so:
`
import { createStore, applyMiddleware, compose } from "redux";
import thunk from "redux-thunk";
import rootReducer from "./reducers";

const initialState = {};

const middleware = [thunk];

const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;

const store = createStore(
  rootReducer,
  initialState,
  composeEnhancers(applyMiddleware(...middleware))
);

export default store;

`
